version: '3.1'

services:   #https://www.bezkoder.com/docker-mern/

  python10:
    image: ${PYTHON_IMAGE}
    command: ["tail", "-F", "anything"]
    container_name: ${PYTHON_SERVICE_NAME}
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - $HOME:$PYTHON_CONTAINER_HOME
      - $HOME/.Xauthority:$HOME/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro

  gcc11:
    image: ${GCC_IMAGE}
    command: ["tail", "-F", "anything"]
    container_name: ${GCC_SERVICE_NAME}
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - $HOME:/$GCC_CONTAINER_HOME
      - $HOME/.Xauthority:$HOME/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro

  java11:
    image: ${JAVA_IMAGE}
    command: ["tail", "-F", "anything"]
    container_name: ${JAVA_SERVICE_NAME}
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - $HOME:$JAVA_CONTAINER_HOME
      - $HOME:/root
      - $HOME/.Xauthority:$HOME/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro

  apache:
    image: ${APACHE_IMAGE}
    container_name: ${APACHE_SERVICE_NAME}
    ports:
      - ${APACHE_PORT}:80
    volumes:
      - $HOME/cse/code/apache/php/p1:/var/www/html
      - $HOME/cse/code/apache/logs:/var/log/apache2
      #- $HOME/cse/code/apache/php/php.ini:/usr/local/etc/php/php.ini'
  
  mariadb:
    image: ${MARIADB_IMAGE}
    container_name: ${MARIADB_SERVICE_NAME}
    entrypoint: custom-docker-entrypoint.sh
    command: ["mariadbd", "--user=root"]
    networks:
      default:
        aliases:
          - db
    volumes: 
      - ./config_files/mariadb/custom-docker-entrypoint.sh:/usr/local/bin/custom-docker-entrypoint.sh 
      - mariadb-data:/var/lib/mysql
    environment:
      TZ: "Asia/Kolkata"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "cse_db"
      MYSQL_USER: "cse"
      MYSQL_PASSWORD: "password"

  adminer:
    image: ${ADMINER_IMAGE}
    container_name: ${ADMINER_SERVICE_NAME}
    restart: 'always'
    ports:
      - ${ADMINER_PORT}:8080

  mongodb:
    image: ${MONGODB_IMAGE}
    container_name: ${MONGODB_SERVICE_NAME}
    #restart: always   #unless-stopped
    networks:
      default:
        aliases:
          - db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongoadmin: #http://localhost:9101
    image: ${MONGODB_ADMIN_IMAGE}
    container_name: ${MONGO_ADMIN_SERVICE_NAME}
    #restart: always
    ports:
      - ${MONGO_ADMIN_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  npm:
    image: ${NPM_IMAGE}
    container_name: ${NPM_SERVICE_NAME}
    entrypoint: []
    command: ["tail", "-F", "anything"]
    #restart: always   #unless-stopped
    volumes:
      - $HOME:/root
    ports:
      - ${NODE_PORT}:7000
      - ${NODE_PORT1}:7001
      - ${NODE_PORT2}:7002
      - ${NODE_PORT3}:7003
      - ${NODE_PORT4}:7004

# git config --global http.sslverify "false"
# https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage
  git:
    image: ${GIT_IMAGE}
    container_name: ${GIT_SERVICE_NAME}
    entrypoint: []
    command: ["tail", "-F", "anything"]
    volumes:
      - $HOME:$GIT_CONTAINER_HOME
      - ./config_files/git/resolv.conf:/etc/resolv.conf
      - ./config_files/git/.gitconfig:/root/.gitconfig
      - $HOME/.ssh:/root/.ssh
    network_mode: host

volumes:
  mariadb-data:

  #portainer: image: portainer/portainer-ce
  #vscodeserver: image: codercom/code-server:latest   #gitpod/openvscode-server


#--cap-add SYS_ADMIN --cap-add MKNOD --device /dev/fuse:mrw

#xhost +
#docker run --rm -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix 

#user: "$(id -u):$(id -g)"
