version: '3.1'

services:   #https://www.bezkoder.com/docker-mern/

  mongo:
    image: mongo
    container_name: mongodb
    #restart: always   #unless-stopped
    networks:
      default:
        aliases:
          - db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-admin: #http://localhost:9101
    image: mongo-express
    container_name: mexpress
    restart: always
    ports:
      - 9101:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  git:
    image: alpine/git:latest
    container_name: git
    entrypoint: []
    command: ["tail", "-F", "anything"]
    #restart: always   #unless-stopped
    volumes:
      - $HOME:/home/newuser
    # docker-compose exec git /bin/sh
    # docker-compose up -d git


  node16:
    image: node:16-bullseye
    container_name: node16
    entrypoint: []
    command: ["tail", "-F", "anything"]
    #restart: always   #unless-stopped
    volumes:
      - $HOME:/home/newuser
    # docker-compose exec node16 /bin/sh
    # docker-compose up -d node16