#!/bin/bash

createLogFile () {

	if [ ! -f "$LOG_FILE" ]; then
		touch $LOG_FILE
		return 0;
	fi

	fileSize="$(du -sh  $LOG_FILE)"
	arrIN=(${fileSize//./ })
	if [ "$arrIN" -gt "7" ]; then
		echo "$(date)" > $LOG_FILE
	fi
}

params=''

function setParams () {
	params=''
	args=("$@") 
	ELEMENTS=${#args[@]}
	for (( i=3;i<$ELEMENTS;i++)); do 
    	#echo ${args[${i}]} 
    	params+=${args[${i}]}
    	params+=" "
	done
}

function exec_docker () {
	createLogFile
	dir_mapped_in_container="${PWD/$HOME/"$CONTAINER_HOME"}"
	docker-compose --file "$2" up -d "$1" 2>> $LOG_FILE
	setParams "$@"
	echo $params
	docker-compose --file $2 exec -w ${dir_mapped_in_container} $1  $3  $params
}

function start_docker () {
	docker-compose --file "$2" up -d "$1"
}

function stop_docker () {
	docker-compose --file "$2" stop "$1"
}

function restart_docker () {
	docker-compose --file "$2" restart "$1"
}