#!/bin/bash

CUREENT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
PARENT_DIR="$(dirname "$CUREENT_DIR")"

COMPOSE_FILE=$PARENT_DIR/docker-compose.yml
source $PARENT_DIR/.env
source $CUREENT_DIR/docker_services

function testThisScript () {
    echo  $CUREENT_DIR
    echo  $PARENT_DIR
    echo  $PARENT_DIR/.env
    echo  $COMPOSE_FILE
    echo "${PWD/$HOME/"$CONTAINER_HOME"}"
    echo  $LOG_FILE
}

exec_docker $GCC_SERVICE_NAME $COMPOSE_FILE $CONTAINER_HOME gcc "$@"

