# https://github.com/flutter/flutter/blob/master/dev/ci/docker_linux/Dockerfile
# https://community.kde.org/Android/Environment_via_Container
# https://itnext.io/flutter-with-wsl-2-69ba8fc7682f
# https://medium.joshkautz.com/installing-flutter-2-0-on-wsl2-2fbf0a354c78
# https://medium.com/@adhbbam/install-flutter-on-wsl2-and-run-apps-directly-in-wsa-or-in-a-physical-device-using-adb-3602f2053f8e
# https://ferilukmansyah.medium.com/setup-flutter-with-android-studio-in-linux-see-this-tips-e1f9327f6a2


FROM ubuntu:18.04

# Prerequisites
RUN apt update && apt install -y curl git unzip xz-utils zip libglu1-mesa openjdk-8-jdk wget

# Set up new user
#RUN useradd -ms /bin/bash developer
#USER developer
#WORKDIR /home/developer

# Prepare Android directories and system variables
RUN mkdir -p Android/sdk
ENV ANDROID_SDK_ROOT /home/developer/Android/sdk
RUN mkdir -p .android && touch .android/repositories.cfg

# Set up Android SDK
RUN wget -O sdk-tools.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
RUN unzip sdk-tools.zip && rm sdk-tools.zip
RUN mv tools Android/sdk/tools
RUN cd Android/sdk/tools/bin && yes | ./sdkmanager --licenses
RUN cd Android/sdk/tools/bin && ./sdkmanager "build-tools;29.0.2" "patcher;v4" "platform-tools" "platforms;android-29" "sources;android-29"
ENV PATH "$PATH:/home/developer/Android/sdk/platform-tools"

# Download Flutter SDK
RUN git clone https://github.com/flutter/flutter.git -b stable
ENV PATH "$PATH:/home/developer/flutter/bin"

# Run basic check to download Dark SDK
RUN flutter doctor